#!/usr/bin/env node
/**
 * Generates src/catalog.generated.ts by scanning src/tools/ for tool modules.
 *
 * Every file in src/tools/ is expected to export `schema` (ToolSchema) and
 * `meta` (ToolMeta). This script emits a file that imports those from each
 * module and assembles the `toolCatalog`. Because it globs the directory,
 * adding a new tool file is picked up automatically — there is no central
 * list to maintain. Because the generated file *imports* schema/meta (rather
 * than copying their values), the catalog can never drift from the tools.
 *
 * Run via `npm run gen:catalog` (also runs on build and pre-commit).
 */
import { readdirSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const toolsDir = resolve(here, '../src/tools');
const outFile = resolve(here, '../src/catalog.generated.ts');

const files = readdirSync(toolsDir)
  .filter((f) => f.endsWith('.ts') && !f.endsWith('.d.ts'))
  .sort();

const tools = files.map((file, i) => ({
  module: `./tools/${file.replace(/\.ts$/, '.js')}`,
  schema: `s${i}`,
  meta: `m${i}`,
}));

const imports = tools
  .map((t) => `import { schema as ${t.schema}, meta as ${t.meta} } from '${t.module}';`)
  .join('\n');

const entries = tools
  .map(
    (t) =>
      `  { name: ${t.schema}.name, description: ${t.schema}.description, ` +
      `factory: ${t.meta}.factory, requiresApiKey: ${t.meta}.requiresApiKey, ` +
      `parameters: ${t.schema}.parameters },`
  )
  .join('\n');

const content = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-catalog.mjs — DO NOT EDIT BY HAND.
// Regenerate with: npm run gen:catalog (runs automatically on build & pre-commit).
// Source of truth: the schema + meta exports of each module in src/tools/.
import type { ToolInfo } from './types.js';
${imports}

/** Every pre-built tool in this version of @jambonz/tools. */
export const toolCatalog: readonly ToolInfo[] = [
${entries}
];

/**
 * List all pre-built tools available in this version of \`@jambonz/tools\`.
 *
 * Use this to check whether a ready-made tool already covers a need before
 * hand-rolling one. To use a tool, import the named \`factory\`, pass its
 * \`.schema\` to \`llmOptions.tools\`, and wire it with \`registerTools()\`.
 */
export function listTools(): ToolInfo[] {
  return [...toolCatalog];
}
`;

// Only write when changed, so the pre-commit hook is a no-op on clean trees.
let existing = '';
try {
  existing = readFileSync(outFile, 'utf8');
} catch {
  /* file does not exist yet */
}
if (existing !== content) {
  writeFileSync(outFile, content);
  console.log(`generated ${outFile} (${tools.length} tools)`);
} else {
  console.log(`catalog up to date (${tools.length} tools)`);
}
