/* eslint-disable */
// AUTO-GENERATED by scripts/generate-catalog.mjs — DO NOT EDIT BY HAND.
// Regenerate with: npm run gen:catalog (runs automatically on build & pre-commit).
// Source of truth: the schema + meta exports of each module in src/tools/.
import type { ToolInfo } from './types.js';
import { schema as s0, meta as m0 } from './tools/calculator.js';
import { schema as s1, meta as m1 } from './tools/datetime.js';
import { schema as s2, meta as m2 } from './tools/tavily-search.js';
import { schema as s3, meta as m3 } from './tools/weather.js';
import { schema as s4, meta as m4 } from './tools/wikipedia.js';

/** Every pre-built tool in this version of @jambonz/tools. */
export const toolCatalog: readonly ToolInfo[] = [
  { name: s0.name, description: s0.description, factory: m0.factory, requiresApiKey: m0.requiresApiKey, parameters: s0.parameters },
  { name: s1.name, description: s1.description, factory: m1.factory, requiresApiKey: m1.requiresApiKey, parameters: s1.parameters },
  { name: s2.name, description: s2.description, factory: m2.factory, requiresApiKey: m2.requiresApiKey, parameters: s2.parameters },
  { name: s3.name, description: s3.description, factory: m3.factory, requiresApiKey: m3.requiresApiKey, parameters: s3.parameters },
  { name: s4.name, description: s4.description, factory: m4.factory, requiresApiKey: m4.requiresApiKey, parameters: s4.parameters },
];

/**
 * List all pre-built tools available in this version of `@jambonz/tools`.
 *
 * Use this to check whether a ready-made tool already covers a need before
 * hand-rolling one. To use a tool, import the named `factory`, pass its
 * `.schema` to `llmOptions.tools`, and wire it with `registerTools()`.
 */
export function listTools(): ToolInfo[] {
  return [...toolCatalog];
}
